//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3082.
// 
namespace Ushahidi.Map.Geocode.Staging {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IGeocodeService", Namespace="http://dev.virtualearth.net/webservices/v1/geocode")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestBase))]
    public partial class GeocodeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public GeocodeService() {
            this.Url = "http://staging.dev.virtualearth.net/webservices/v1/geocodeservice/GeocodeService." +
                "svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
            "ode", RequestNamespace="http://dev.virtualearth.net/webservices/v1/geocode/contracts", ResponseNamespace="http://dev.virtualearth.net/webservices/v1/geocode/contracts", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GeocodeResponse Geocode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] GeocodeRequest request) {
            object[] results = this.Invoke("Geocode", new object[] {
                        request});
            return ((GeocodeResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGeocode(GeocodeRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Geocode", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public GeocodeResponse EndGeocode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GeocodeResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
            "rseGeocode", RequestNamespace="http://dev.virtualearth.net/webservices/v1/geocode/contracts", ResponseNamespace="http://dev.virtualearth.net/webservices/v1/geocode/contracts", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GeocodeResponse ReverseGeocode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ReverseGeocodeRequest request) {
            object[] results = this.Invoke("ReverseGeocode", new object[] {
                        request});
            return ((GeocodeResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReverseGeocode(ReverseGeocodeRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReverseGeocode", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public GeocodeResponse EndReverseGeocode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GeocodeResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/geocode")]
    public partial class GeocodeRequest : RequestBase {
        
        private Address addressField;
        
        private GeocodeOptions optionsField;
        
        private string queryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GeocodeOptions Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Address {
        
        private string addressLineField;
        
        private string adminDistrictField;
        
        private string countryRegionField;
        
        private string districtField;
        
        private string formattedAddressField;
        
        private string localityField;
        
        private string postalCodeField;
        
        private string postalTownField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdminDistrict {
            get {
                return this.adminDistrictField;
            }
            set {
                this.adminDistrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryRegion {
            get {
                return this.countryRegionField;
            }
            set {
                this.countryRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FormattedAddress {
            get {
                return this.formattedAddressField;
            }
            set {
                this.formattedAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostalTown {
            get {
                return this.postalTownField;
            }
            set {
                this.postalTownField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class GeocodeResult {
        
        private Address addressField;
        
        private Rectangle bestViewField;
        
        private Confidence confidenceField;
        
        private bool confidenceFieldSpecified;
        
        private string displayNameField;
        
        private string entityTypeField;
        
        private GeocodeLocation[] locationsField;
        
        private string[] matchCodesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Rectangle BestView {
            get {
                return this.bestViewField;
            }
            set {
                this.bestViewField = value;
            }
        }
        
        /// <remarks/>
        public Confidence Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfidenceSpecified {
            get {
                return this.confidenceFieldSpecified;
            }
            set {
                this.confidenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EntityType {
            get {
                return this.entityTypeField;
            }
            set {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public GeocodeLocation[] Locations {
            get {
                return this.locationsField;
            }
            set {
                this.locationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] MatchCodes {
            get {
                return this.matchCodesField;
            }
            set {
                this.matchCodesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Rectangle : ShapeBase {
        
        private Location northeastField;
        
        private Location southwestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Northeast {
            get {
                return this.northeastField;
            }
            set {
                this.northeastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Southwest {
            get {
                return this.southwestField;
            }
            set {
                this.southwestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GeocodeLocation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserLocation))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Location {
        
        private double altitudeField;
        
        private bool altitudeFieldSpecified;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        /// <remarks/>
        public double Altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AltitudeSpecified {
            get {
                return this.altitudeFieldSpecified;
            }
            set {
                this.altitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class GeocodeLocation : Location {
        
        private string calculationMethodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CalculationMethod {
            get {
                return this.calculationMethodField;
            }
            set {
                this.calculationMethodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserLocation : Location {
        
        private Confidence confidenceField;
        
        private bool confidenceFieldSpecified;
        
        /// <remarks/>
        public Confidence Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfidenceSpecified {
            get {
                return this.confidenceFieldSpecified;
            }
            set {
                this.confidenceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum Confidence {
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polygon))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Circle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rectangle))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ShapeBase {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Polygon : ShapeBase {
        
        private Location[] verticesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Location[] Vertices {
            get {
                return this.verticesField;
            }
            set {
                this.verticesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Circle : ShapeBase {
        
        private Location centerField;
        
        private DistanceUnit distanceUnitField;
        
        private bool distanceUnitFieldSpecified;
        
        private double radiusField;
        
        private bool radiusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        public DistanceUnit DistanceUnit {
            get {
                return this.distanceUnitField;
            }
            set {
                this.distanceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceUnitSpecified {
            get {
                return this.distanceUnitFieldSpecified;
            }
            set {
                this.distanceUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RadiusSpecified {
            get {
                return this.radiusFieldSpecified;
            }
            set {
                this.radiusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DistanceUnit {
        
        /// <remarks/>
        Kilometer,
        
        /// <remarks/>
        Mile,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ResponseSummary {
        
        private AuthenticationResultCode authenticationResultCodeField;
        
        private bool authenticationResultCodeFieldSpecified;
        
        private string copyrightField;
        
        private string faultReasonField;
        
        private ResponseStatusCode statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string traceIdField;
        
        /// <remarks/>
        public AuthenticationResultCode AuthenticationResultCode {
            get {
                return this.authenticationResultCodeField;
            }
            set {
                this.authenticationResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AuthenticationResultCodeSpecified {
            get {
                return this.authenticationResultCodeFieldSpecified;
            }
            set {
                this.authenticationResultCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FaultReason {
            get {
                return this.faultReasonField;
            }
            set {
                this.faultReasonField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatusCode StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TraceId {
            get {
                return this.traceIdField;
            }
            set {
                this.traceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum AuthenticationResultCode {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        NoCredentials,
        
        /// <remarks/>
        ValidCredentials,
        
        /// <remarks/>
        InvalidCredentials,
        
        /// <remarks/>
        CredentialsExpired,
        
        /// <remarks/>
        NotAuthorized,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum ResponseStatusCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        ServerError,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GeocodeResponse))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ResponseBase {
        
        private ResponseSummary responseSummaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseSummary ResponseSummary {
            get {
                return this.responseSummaryField;
            }
            set {
                this.responseSummaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/geocode")]
    public partial class GeocodeResponse : ResponseBase {
        
        private GeocodeResult[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
        public GeocodeResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfidenceFilter))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/geocode")]
    public partial class FilterBase {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/geocode")]
    public partial class ConfidenceFilter : FilterBase {
        
        private Confidence minimumConfidenceField;
        
        private bool minimumConfidenceFieldSpecified;
        
        /// <remarks/>
        public Confidence MinimumConfidence {
            get {
                return this.minimumConfidenceField;
            }
            set {
                this.minimumConfidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinimumConfidenceSpecified {
            get {
                return this.minimumConfidenceFieldSpecified;
            }
            set {
                this.minimumConfidenceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/geocode")]
    public partial class GeocodeOptions {
        
        private System.Nullable<int> countField;
        
        private bool countFieldSpecified;
        
        private FilterBase[] filtersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public FilterBase[] Filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class SizeOfint {
        
        private int heightField;
        
        private bool heightFieldSpecified;
        
        private int widthField;
        
        private bool widthFieldSpecified;
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Heading {
        
        private double orientationField;
        
        private bool orientationFieldSpecified;
        
        /// <remarks/>
        public double Orientation {
            get {
                return this.orientationField;
            }
            set {
                this.orientationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrientationSpecified {
            get {
                return this.orientationFieldSpecified;
            }
            set {
                this.orientationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserProfile {
        
        private Heading currentHeadingField;
        
        private UserLocation currentLocationField;
        
        private DeviceType deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private DistanceUnit distanceUnitField;
        
        private bool distanceUnitFieldSpecified;
        
        private string iPAddressField;
        
        private ShapeBase mapViewField;
        
        private SizeOfint screenSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Heading CurrentHeading {
            get {
                return this.currentHeadingField;
            }
            set {
                this.currentHeadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserLocation CurrentLocation {
            get {
                return this.currentLocationField;
            }
            set {
                this.currentLocationField = value;
            }
        }
        
        /// <remarks/>
        public DeviceType DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeviceTypeSpecified {
            get {
                return this.deviceTypeFieldSpecified;
            }
            set {
                this.deviceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DistanceUnit DistanceUnit {
            get {
                return this.distanceUnitField;
            }
            set {
                this.distanceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceUnitSpecified {
            get {
                return this.distanceUnitFieldSpecified;
            }
            set {
                this.distanceUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ShapeBase MapView {
            get {
                return this.mapViewField;
            }
            set {
                this.mapViewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SizeOfint ScreenSize {
            get {
                return this.screenSizeField;
            }
            set {
                this.screenSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DeviceType {
        
        /// <remarks/>
        Desktop,
        
        /// <remarks/>
        Mobile,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ExecutionOptions {
        
        private bool suppressFaultsField;
        
        private bool suppressFaultsFieldSpecified;
        
        /// <remarks/>
        public bool SuppressFaults {
            get {
                return this.suppressFaultsField;
            }
            set {
                this.suppressFaultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuppressFaultsSpecified {
            get {
                return this.suppressFaultsFieldSpecified;
            }
            set {
                this.suppressFaultsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Credentials {
        
        private string applicationIdField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReverseGeocodeRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GeocodeRequest))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class RequestBase {
        
        private Credentials credentialsField;
        
        private string cultureField;
        
        private ExecutionOptions executionOptionsField;
        
        private UserProfile userProfileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Credentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExecutionOptions ExecutionOptions {
            get {
                return this.executionOptionsField;
            }
            set {
                this.executionOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserProfile UserProfile {
            get {
                return this.userProfileField;
            }
            set {
                this.userProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/geocode")]
    public partial class ReverseGeocodeRequest : RequestBase {
        
        private Location locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
}
