//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3082.
// 
namespace Ushahidi.Map.Routing.Staging {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IRouteService", Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestBase))]
    public partial class RouteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public RouteService() {
            this.Url = "http://staging.dev.virtualearth.net/webservices/v1/routeservice/routeservice.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/Calculat" +
            "eRoute", RequestNamespace="http://dev.virtualearth.net/webservices/v1/route/contracts", ResponseNamespace="http://dev.virtualearth.net/webservices/v1/route/contracts", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteResponse CalculateRoute([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RouteRequest request) {
            object[] results = this.Invoke("CalculateRoute", new object[] {
                        request});
            return ((RouteResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCalculateRoute(RouteRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CalculateRoute", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public RouteResponse EndCalculateRoute(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RouteResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.virtualearth.net/webservices/v1/route/contracts/IRouteService/Calculat" +
            "eRoutesFromMajorRoads", RequestNamespace="http://dev.virtualearth.net/webservices/v1/route/contracts", ResponseNamespace="http://dev.virtualearth.net/webservices/v1/route/contracts", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MajorRoutesResponse CalculateRoutesFromMajorRoads([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MajorRoutesRequest request) {
            object[] results = this.Invoke("CalculateRoutesFromMajorRoads", new object[] {
                        request});
            return ((MajorRoutesResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCalculateRoutesFromMajorRoads(MajorRoutesRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CalculateRoutesFromMajorRoads", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public MajorRoutesResponse EndCalculateRoutesFromMajorRoads(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MajorRoutesResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteRequest : RequestBase {
        
        private RouteOptions optionsField;
        
        private Waypoint[] waypointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteOptions Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Waypoint[] Waypoints {
            get {
                return this.waypointsField;
            }
            set {
                this.waypointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MajorRoutesOptions))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteOptions {
        
        private TravelMode modeField;
        
        private bool modeFieldSpecified;
        
        private RouteOptimization optimizationField;
        
        private bool optimizationFieldSpecified;
        
        private RoutePathType routePathTypeField;
        
        private bool routePathTypeFieldSpecified;
        
        private TrafficUsage trafficUsageField;
        
        private bool trafficUsageFieldSpecified;
        
        /// <remarks/>
        public TravelMode Mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModeSpecified {
            get {
                return this.modeFieldSpecified;
            }
            set {
                this.modeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public RouteOptimization Optimization {
            get {
                return this.optimizationField;
            }
            set {
                this.optimizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptimizationSpecified {
            get {
                return this.optimizationFieldSpecified;
            }
            set {
                this.optimizationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public RoutePathType RoutePathType {
            get {
                return this.routePathTypeField;
            }
            set {
                this.routePathTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoutePathTypeSpecified {
            get {
                return this.routePathTypeFieldSpecified;
            }
            set {
                this.routePathTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TrafficUsage TrafficUsage {
            get {
                return this.trafficUsageField;
            }
            set {
                this.trafficUsageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TrafficUsageSpecified {
            get {
                return this.trafficUsageFieldSpecified;
            }
            set {
                this.trafficUsageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum TravelMode {
        
        /// <remarks/>
        Driving,
        
        /// <remarks/>
        Walking,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum RouteOptimization {
        
        /// <remarks/>
        MinimizeTime,
        
        /// <remarks/>
        MinimizeDistance,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum RoutePathType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Points,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum TrafficUsage {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        TrafficBasedTime,
        
        /// <remarks/>
        TrafficBasedRouteAndTime,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RoutePath {
        
        private Location[] pointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
        public Location[] Points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GeocodeLocation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserLocation))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Location {
        
        private double altitudeField;
        
        private bool altitudeFieldSpecified;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        /// <remarks/>
        public double Altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AltitudeSpecified {
            get {
                return this.altitudeFieldSpecified;
            }
            set {
                this.altitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class GeocodeLocation : Location {
        
        private string calculationMethodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CalculationMethod {
            get {
                return this.calculationMethodField;
            }
            set {
                this.calculationMethodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserLocation : Location {
        
        private Confidence confidenceField;
        
        private bool confidenceFieldSpecified;
        
        /// <remarks/>
        public Confidence Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfidenceSpecified {
            get {
                return this.confidenceFieldSpecified;
            }
            set {
                this.confidenceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum Confidence {
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class ItineraryItemWarning {
        
        private ItineraryWarningSeverity severityField;
        
        private bool severityFieldSpecified;
        
        private string textField;
        
        private ItineraryWarningType warningTypeField;
        
        private bool warningTypeFieldSpecified;
        
        /// <remarks/>
        public ItineraryWarningSeverity Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeveritySpecified {
            get {
                return this.severityFieldSpecified;
            }
            set {
                this.severityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public ItineraryWarningType WarningType {
            get {
                return this.warningTypeField;
            }
            set {
                this.warningTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarningTypeSpecified {
            get {
                return this.warningTypeFieldSpecified;
            }
            set {
                this.warningTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ItineraryWarningSeverity {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        LowImpact,
        
        /// <remarks/>
        Minor,
        
        /// <remarks/>
        Moderate,
        
        /// <remarks/>
        Serious,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ItineraryWarningType {
        
        /// <remarks/>
        Accident,
        
        /// <remarks/>
        AdminDivisionChange,
        
        /// <remarks/>
        BlockedRoad,
        
        /// <remarks/>
        CheckTimetable,
        
        /// <remarks/>
        Congestion,
        
        /// <remarks/>
        CountryChange,
        
        /// <remarks/>
        DisabledVehicle,
        
        /// <remarks/>
        GateAccess,
        
        /// <remarks/>
        GetOffTransit,
        
        /// <remarks/>
        GetOnTransit,
        
        /// <remarks/>
        IllegalUTurn,
        
        /// <remarks/>
        MassTransit,
        
        /// <remarks/>
        Miscellaneous,
        
        /// <remarks/>
        NoIncident,
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        OtherNews,
        
        /// <remarks/>
        OtherTrafficIncidents,
        
        /// <remarks/>
        PlannedEvent,
        
        /// <remarks/>
        PrivateRoad,
        
        /// <remarks/>
        RestrictedTurn,
        
        /// <remarks/>
        RoadClosures,
        
        /// <remarks/>
        RoadHazard,
        
        /// <remarks/>
        ScheduledConstruction,
        
        /// <remarks/>
        SeasonalClosures,
        
        /// <remarks/>
        Tollbooth,
        
        /// <remarks/>
        TollRoad,
        
        /// <remarks/>
        TrafficFlow,
        
        /// <remarks/>
        UnpavedRoad,
        
        /// <remarks/>
        UnscheduledConstruction,
        
        /// <remarks/>
        Weather,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteSummary {
        
        private Rectangle boundingRectangleField;
        
        private double distanceField;
        
        private bool distanceFieldSpecified;
        
        private long timeInSecondsField;
        
        private bool timeInSecondsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Rectangle BoundingRectangle {
            get {
                return this.boundingRectangleField;
            }
            set {
                this.boundingRectangleField = value;
            }
        }
        
        /// <remarks/>
        public double Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceSpecified {
            get {
                return this.distanceFieldSpecified;
            }
            set {
                this.distanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long TimeInSeconds {
            get {
                return this.timeInSecondsField;
            }
            set {
                this.timeInSecondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeInSecondsSpecified {
            get {
                return this.timeInSecondsFieldSpecified;
            }
            set {
                this.timeInSecondsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Rectangle : ShapeBase {
        
        private Location northeastField;
        
        private Location southwestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Northeast {
            get {
                return this.northeastField;
            }
            set {
                this.northeastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Southwest {
            get {
                return this.southwestField;
            }
            set {
                this.southwestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polygon))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Circle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rectangle))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ShapeBase {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Polygon : ShapeBase {
        
        private Location[] verticesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Location[] Vertices {
            get {
                return this.verticesField;
            }
            set {
                this.verticesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Circle : ShapeBase {
        
        private Location centerField;
        
        private DistanceUnit distanceUnitField;
        
        private bool distanceUnitFieldSpecified;
        
        private double radiusField;
        
        private bool radiusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        public DistanceUnit DistanceUnit {
            get {
                return this.distanceUnitField;
            }
            set {
                this.distanceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceUnitSpecified {
            get {
                return this.distanceUnitFieldSpecified;
            }
            set {
                this.distanceUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RadiusSpecified {
            get {
                return this.radiusFieldSpecified;
            }
            set {
                this.radiusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DistanceUnit {
        
        /// <remarks/>
        Kilometer,
        
        /// <remarks/>
        Mile,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class ItineraryItemHint {
        
        private ItineraryItemHintType hintTypeField;
        
        private bool hintTypeFieldSpecified;
        
        private string textField;
        
        /// <remarks/>
        public ItineraryItemHintType HintType {
            get {
                return this.hintTypeField;
            }
            set {
                this.hintTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HintTypeSpecified {
            get {
                return this.hintTypeFieldSpecified;
            }
            set {
                this.hintTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ItineraryItemHintType {
        
        /// <remarks/>
        PreviousIntersection,
        
        /// <remarks/>
        NextIntersection,
        
        /// <remarks/>
        Landmark,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class ItineraryItem {
        
        private string compassDirectionField;
        
        private ItineraryItemHint[] hintsField;
        
        private Location locationField;
        
        private ManeuverType maneuverTypeField;
        
        private bool maneuverTypeFieldSpecified;
        
        private RouteSummary summaryField;
        
        private string textField;
        
        private ItineraryItemWarning[] warningsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CompassDirection {
            get {
                return this.compassDirectionField;
            }
            set {
                this.compassDirectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ItineraryItemHint[] Hints {
            get {
                return this.hintsField;
            }
            set {
                this.hintsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public ManeuverType ManeuverType {
            get {
                return this.maneuverTypeField;
            }
            set {
                this.maneuverTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ManeuverTypeSpecified {
            get {
                return this.maneuverTypeFieldSpecified;
            }
            set {
                this.maneuverTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteSummary Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ItineraryItemWarning[] Warnings {
            get {
                return this.warningsField;
            }
            set {
                this.warningsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public enum ManeuverType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        DepartStart,
        
        /// <remarks/>
        DepartIntermediateStop,
        
        /// <remarks/>
        DepartIntermediateStopReturning,
        
        /// <remarks/>
        ArriveFinish,
        
        /// <remarks/>
        ArriveIntermediateStop,
        
        /// <remarks/>
        TurnLeft,
        
        /// <remarks/>
        TurnRight,
        
        /// <remarks/>
        TurnBack,
        
        /// <remarks/>
        UTurn,
        
        /// <remarks/>
        TurnToStayLeft,
        
        /// <remarks/>
        TurnToStayRight,
        
        /// <remarks/>
        BearLeft,
        
        /// <remarks/>
        BearRight,
        
        /// <remarks/>
        KeepToStayLeft,
        
        /// <remarks/>
        KeepToStayRight,
        
        /// <remarks/>
        KeepToStayStraight,
        
        /// <remarks/>
        KeepLeft,
        
        /// <remarks/>
        KeepRight,
        
        /// <remarks/>
        KeepStraight,
        
        /// <remarks/>
        Take,
        
        /// <remarks/>
        TakeRampLeft,
        
        /// <remarks/>
        TakeRampRight,
        
        /// <remarks/>
        TakeRampStraight,
        
        /// <remarks/>
        KeepOnrampLeft,
        
        /// <remarks/>
        KeepOnrampRight,
        
        /// <remarks/>
        KeepOnrampStraight,
        
        /// <remarks/>
        Merge,
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        RoadNameChange,
        
        /// <remarks/>
        EnterRoundabout,
        
        /// <remarks/>
        ExitRoundabout,
        
        /// <remarks/>
        TurnRightThenTurnRight,
        
        /// <remarks/>
        TurnRightThenTurnLeft,
        
        /// <remarks/>
        TurnRightThenBearRight,
        
        /// <remarks/>
        TurnRightThenBearLeft,
        
        /// <remarks/>
        TurnLeftThenTurnLeft,
        
        /// <remarks/>
        TurnLeftThenTurnRight,
        
        /// <remarks/>
        TurnLeftThenBearLeft,
        
        /// <remarks/>
        TurnLeftThenBearRight,
        
        /// <remarks/>
        BearRightThenTurnRight,
        
        /// <remarks/>
        BearRightThenTurnLeft,
        
        /// <remarks/>
        BearRightThenBearRight,
        
        /// <remarks/>
        BearRightThenBearLeft,
        
        /// <remarks/>
        BearLeftThenTurnLeft,
        
        /// <remarks/>
        BearLeftThenTurnRight,
        
        /// <remarks/>
        BearLeftThenBearRight,
        
        /// <remarks/>
        BearLeftThenBearLeft,
        
        /// <remarks/>
        RampThenHighwayRight,
        
        /// <remarks/>
        RampThenHighwayLeft,
        
        /// <remarks/>
        RampToHighwayStraight,
        
        /// <remarks/>
        EnterThenExitRoundabout,
        
        /// <remarks/>
        BearThenMerge,
        
        /// <remarks/>
        TurnThenMerge,
        
        /// <remarks/>
        BearThenKeep,
        
        /// <remarks/>
        Transfer,
        
        /// <remarks/>
        Wait,
        
        /// <remarks/>
        TakeTransit,
        
        /// <remarks/>
        Walk,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteLeg {
        
        private Location actualEndField;
        
        private Location actualStartField;
        
        private ItineraryItem[] itineraryField;
        
        private RouteSummary summaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location ActualEnd {
            get {
                return this.actualEndField;
            }
            set {
                this.actualEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location ActualStart {
            get {
                return this.actualStartField;
            }
            set {
                this.actualStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ItineraryItem[] Itinerary {
            get {
                return this.itineraryField;
            }
            set {
                this.itineraryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteSummary Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteResult {
        
        private RouteLeg[] legsField;
        
        private RoutePath routePathField;
        
        private RouteSummary summaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public RouteLeg[] Legs {
            get {
                return this.legsField;
            }
            set {
                this.legsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RoutePath RoutePath {
            get {
                return this.routePathField;
            }
            set {
                this.routePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteSummary Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ResponseSummary {
        
        private AuthenticationResultCode authenticationResultCodeField;
        
        private bool authenticationResultCodeFieldSpecified;
        
        private string copyrightField;
        
        private string faultReasonField;
        
        private ResponseStatusCode statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string traceIdField;
        
        /// <remarks/>
        public AuthenticationResultCode AuthenticationResultCode {
            get {
                return this.authenticationResultCodeField;
            }
            set {
                this.authenticationResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AuthenticationResultCodeSpecified {
            get {
                return this.authenticationResultCodeFieldSpecified;
            }
            set {
                this.authenticationResultCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FaultReason {
            get {
                return this.faultReasonField;
            }
            set {
                this.faultReasonField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatusCode StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TraceId {
            get {
                return this.traceIdField;
            }
            set {
                this.traceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum AuthenticationResultCode {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        NoCredentials,
        
        /// <remarks/>
        ValidCredentials,
        
        /// <remarks/>
        InvalidCredentials,
        
        /// <remarks/>
        CredentialsExpired,
        
        /// <remarks/>
        NotAuthorized,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum ResponseStatusCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        ServerError,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MajorRoutesResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RouteResponse))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ResponseBase {
        
        private ResponseSummary responseSummaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseSummary ResponseSummary {
            get {
                return this.responseSummaryField;
            }
            set {
                this.responseSummaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class MajorRoutesResponse : ResponseBase {
        
        private RouteResult[] routesField;
        
        private Waypoint[] startingPointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public RouteResult[] Routes {
            get {
                return this.routesField;
            }
            set {
                this.routesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Waypoint[] StartingPoints {
            get {
                return this.startingPointsField;
            }
            set {
                this.startingPointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class Waypoint {
        
        private string descriptionField;
        
        private Location locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class RouteResponse : ResponseBase {
        
        private RouteResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RouteResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class SizeOfint {
        
        private int heightField;
        
        private bool heightFieldSpecified;
        
        private int widthField;
        
        private bool widthFieldSpecified;
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Heading {
        
        private double orientationField;
        
        private bool orientationFieldSpecified;
        
        /// <remarks/>
        public double Orientation {
            get {
                return this.orientationField;
            }
            set {
                this.orientationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrientationSpecified {
            get {
                return this.orientationFieldSpecified;
            }
            set {
                this.orientationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserProfile {
        
        private Heading currentHeadingField;
        
        private UserLocation currentLocationField;
        
        private DeviceType deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private DistanceUnit distanceUnitField;
        
        private bool distanceUnitFieldSpecified;
        
        private string iPAddressField;
        
        private ShapeBase mapViewField;
        
        private SizeOfint screenSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Heading CurrentHeading {
            get {
                return this.currentHeadingField;
            }
            set {
                this.currentHeadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserLocation CurrentLocation {
            get {
                return this.currentLocationField;
            }
            set {
                this.currentLocationField = value;
            }
        }
        
        /// <remarks/>
        public DeviceType DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeviceTypeSpecified {
            get {
                return this.deviceTypeFieldSpecified;
            }
            set {
                this.deviceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DistanceUnit DistanceUnit {
            get {
                return this.distanceUnitField;
            }
            set {
                this.distanceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceUnitSpecified {
            get {
                return this.distanceUnitFieldSpecified;
            }
            set {
                this.distanceUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ShapeBase MapView {
            get {
                return this.mapViewField;
            }
            set {
                this.mapViewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SizeOfint ScreenSize {
            get {
                return this.screenSizeField;
            }
            set {
                this.screenSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DeviceType {
        
        /// <remarks/>
        Desktop,
        
        /// <remarks/>
        Mobile,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ExecutionOptions {
        
        private bool suppressFaultsField;
        
        private bool suppressFaultsFieldSpecified;
        
        /// <remarks/>
        public bool SuppressFaults {
            get {
                return this.suppressFaultsField;
            }
            set {
                this.suppressFaultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuppressFaultsSpecified {
            get {
                return this.suppressFaultsFieldSpecified;
            }
            set {
                this.suppressFaultsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Credentials {
        
        private string applicationIdField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MajorRoutesRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RouteRequest))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class RequestBase {
        
        private Credentials credentialsField;
        
        private string cultureField;
        
        private ExecutionOptions executionOptionsField;
        
        private UserProfile userProfileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Credentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExecutionOptions ExecutionOptions {
            get {
                return this.executionOptionsField;
            }
            set {
                this.executionOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserProfile UserProfile {
            get {
                return this.userProfileField;
            }
            set {
                this.userProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class MajorRoutesRequest : RequestBase {
        
        private Waypoint destinationField;
        
        private MajorRoutesOptions optionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Waypoint Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MajorRoutesOptions Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/route")]
    public partial class MajorRoutesOptions : RouteOptions {
        
        private bool returnRoutesField;
        
        private bool returnRoutesFieldSpecified;
        
        /// <remarks/>
        public bool ReturnRoutes {
            get {
                return this.returnRoutesField;
            }
            set {
                this.returnRoutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnRoutesSpecified {
            get {
                return this.returnRoutesFieldSpecified;
            }
            set {
                this.returnRoutesFieldSpecified = value;
            }
        }
    }
}
