//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3082.
// 
namespace Ushahidi.Map.Imaging.Staging {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IImageryService", Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestBase))]
    public partial class ImageryService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ImageryService() {
            this.Url = "http://staging.dev.virtualearth.net/webservices/v1/imageryservice/imageryservice." +
                "svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetI" +
            "mageryMetadata", RequestNamespace="http://dev.virtualearth.net/webservices/v1/imagery/contracts", ResponseNamespace="http://dev.virtualearth.net/webservices/v1/imagery/contracts", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ImageryMetadataResponse GetImageryMetadata([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ImageryMetadataRequest request) {
            object[] results = this.Invoke("GetImageryMetadata", new object[] {
                        request});
            return ((ImageryMetadataResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetImageryMetadata(ImageryMetadataRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetImageryMetadata", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public ImageryMetadataResponse EndGetImageryMetadata(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ImageryMetadataResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetM" +
            "apUri", RequestNamespace="http://dev.virtualearth.net/webservices/v1/imagery/contracts", ResponseNamespace="http://dev.virtualearth.net/webservices/v1/imagery/contracts", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MapUriResponse GetMapUri([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MapUriRequest request) {
            object[] results = this.Invoke("GetMapUri", new object[] {
                        request});
            return ((MapUriResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetMapUri(MapUriRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetMapUri", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public MapUriResponse EndGetMapUri(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((MapUriResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class ImageryMetadataRequest : RequestBase {
        
        private ImageryMetadataOptions optionsField;
        
        private MapStyle styleField;
        
        private bool styleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ImageryMetadataOptions Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        public MapStyle Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StyleSpecified {
            get {
                return this.styleFieldSpecified;
            }
            set {
                this.styleFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class ImageryMetadataOptions {
        
        private Heading headingField;
        
        private Location locationField;
        
        private bool returnImageryProvidersField;
        
        private bool returnImageryProvidersFieldSpecified;
        
        private UriScheme uriSchemeField;
        
        private bool uriSchemeFieldSpecified;
        
        private System.Nullable<int> zoomLevelField;
        
        private bool zoomLevelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Heading Heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public bool ReturnImageryProviders {
            get {
                return this.returnImageryProvidersField;
            }
            set {
                this.returnImageryProvidersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnImageryProvidersSpecified {
            get {
                return this.returnImageryProvidersFieldSpecified;
            }
            set {
                this.returnImageryProvidersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public UriScheme UriScheme {
            get {
                return this.uriSchemeField;
            }
            set {
                this.uriSchemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UriSchemeSpecified {
            get {
                return this.uriSchemeFieldSpecified;
            }
            set {
                this.uriSchemeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ZoomLevel {
            get {
                return this.zoomLevelField;
            }
            set {
                this.zoomLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZoomLevelSpecified {
            get {
                return this.zoomLevelFieldSpecified;
            }
            set {
                this.zoomLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Heading {
        
        private double orientationField;
        
        private bool orientationFieldSpecified;
        
        /// <remarks/>
        public double Orientation {
            get {
                return this.orientationField;
            }
            set {
                this.orientationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrientationSpecified {
            get {
                return this.orientationFieldSpecified;
            }
            set {
                this.orientationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class RangeOfdateTime {
        
        private System.DateTime fromField;
        
        private bool fromFieldSpecified;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        /// <remarks/>
        public System.DateTime From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FromSpecified {
            get {
                return this.fromFieldSpecified;
            }
            set {
                this.fromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class RangeOfint {
        
        private int fromField;
        
        private bool fromFieldSpecified;
        
        private int toField;
        
        private bool toFieldSpecified;
        
        /// <remarks/>
        public int From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FromSpecified {
            get {
                return this.fromFieldSpecified;
            }
            set {
                this.fromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class CoverageArea {
        
        private Rectangle boundingRectangleField;
        
        private RangeOfint zoomRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Rectangle BoundingRectangle {
            get {
                return this.boundingRectangleField;
            }
            set {
                this.boundingRectangleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RangeOfint ZoomRange {
            get {
                return this.zoomRangeField;
            }
            set {
                this.zoomRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Rectangle : ShapeBase {
        
        private Location northeastField;
        
        private Location southwestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Northeast {
            get {
                return this.northeastField;
            }
            set {
                this.northeastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Southwest {
            get {
                return this.southwestField;
            }
            set {
                this.southwestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GeocodeLocation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserLocation))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Location {
        
        private double altitudeField;
        
        private bool altitudeFieldSpecified;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        /// <remarks/>
        public double Altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AltitudeSpecified {
            get {
                return this.altitudeFieldSpecified;
            }
            set {
                this.altitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class GeocodeLocation : Location {
        
        private string calculationMethodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CalculationMethod {
            get {
                return this.calculationMethodField;
            }
            set {
                this.calculationMethodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserLocation : Location {
        
        private Confidence confidenceField;
        
        private bool confidenceFieldSpecified;
        
        /// <remarks/>
        public Confidence Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfidenceSpecified {
            get {
                return this.confidenceFieldSpecified;
            }
            set {
                this.confidenceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum Confidence {
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchPoint))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polygon))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rectangle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Circle))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ShapeBase {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class SearchPoint : ShapeBase {
        
        private Location pointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Polygon : ShapeBase {
        
        private Location[] verticesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Location[] Vertices {
            get {
                return this.verticesField;
            }
            set {
                this.verticesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Circle : ShapeBase {
        
        private Location centerField;
        
        private DistanceUnit distanceUnitField;
        
        private bool distanceUnitFieldSpecified;
        
        private double radiusField;
        
        private bool radiusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        public DistanceUnit DistanceUnit {
            get {
                return this.distanceUnitField;
            }
            set {
                this.distanceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceUnitSpecified {
            get {
                return this.distanceUnitFieldSpecified;
            }
            set {
                this.distanceUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RadiusSpecified {
            get {
                return this.radiusFieldSpecified;
            }
            set {
                this.radiusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DistanceUnit {
        
        /// <remarks/>
        Kilometer,
        
        /// <remarks/>
        Mile,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class ImageryProvider {
        
        private string attributionField;
        
        private CoverageArea[] coverageAreasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Attribution {
            get {
                return this.attributionField;
            }
            set {
                this.attributionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CoverageArea[] CoverageAreas {
            get {
                return this.coverageAreasField;
            }
            set {
                this.coverageAreasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImageryMetadataBirdseyeResult))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class ImageryMetadataResult {
        
        private SizeOfint imageSizeField;
        
        private string imageUriField;
        
        private string[] imageUriSubdomainsField;
        
        private ImageryProvider[] imageryProvidersField;
        
        private RangeOfdateTime vintageField;
        
        private RangeOfint zoomRangeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SizeOfint ImageSize {
            get {
                return this.imageSizeField;
            }
            set {
                this.imageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ImageUri {
            get {
                return this.imageUriField;
            }
            set {
                this.imageUriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] ImageUriSubdomains {
            get {
                return this.imageUriSubdomainsField;
            }
            set {
                this.imageUriSubdomainsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ImageryProvider[] ImageryProviders {
            get {
                return this.imageryProvidersField;
            }
            set {
                this.imageryProvidersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RangeOfdateTime Vintage {
            get {
                return this.vintageField;
            }
            set {
                this.vintageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RangeOfint ZoomRange {
            get {
                return this.zoomRangeField;
            }
            set {
                this.zoomRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class SizeOfint {
        
        private int heightField;
        
        private bool heightFieldSpecified;
        
        private int widthField;
        
        private bool widthFieldSpecified;
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class ImageryMetadataBirdseyeResult : ImageryMetadataResult {
        
        private Heading headingField;
        
        private int tilesXField;
        
        private bool tilesXFieldSpecified;
        
        private int tilesYField;
        
        private bool tilesYFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Heading Heading {
            get {
                return this.headingField;
            }
            set {
                this.headingField = value;
            }
        }
        
        /// <remarks/>
        public int TilesX {
            get {
                return this.tilesXField;
            }
            set {
                this.tilesXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TilesXSpecified {
            get {
                return this.tilesXFieldSpecified;
            }
            set {
                this.tilesXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TilesY {
            get {
                return this.tilesYField;
            }
            set {
                this.tilesYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TilesYSpecified {
            get {
                return this.tilesYFieldSpecified;
            }
            set {
                this.tilesYFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ResponseSummary {
        
        private AuthenticationResultCode authenticationResultCodeField;
        
        private bool authenticationResultCodeFieldSpecified;
        
        private string copyrightField;
        
        private string faultReasonField;
        
        private ResponseStatusCode statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string traceIdField;
        
        /// <remarks/>
        public AuthenticationResultCode AuthenticationResultCode {
            get {
                return this.authenticationResultCodeField;
            }
            set {
                this.authenticationResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AuthenticationResultCodeSpecified {
            get {
                return this.authenticationResultCodeFieldSpecified;
            }
            set {
                this.authenticationResultCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FaultReason {
            get {
                return this.faultReasonField;
            }
            set {
                this.faultReasonField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatusCode StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TraceId {
            get {
                return this.traceIdField;
            }
            set {
                this.traceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum AuthenticationResultCode {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        NoCredentials,
        
        /// <remarks/>
        ValidCredentials,
        
        /// <remarks/>
        InvalidCredentials,
        
        /// <remarks/>
        CredentialsExpired,
        
        /// <remarks/>
        NotAuthorized,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum ResponseStatusCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        ServerError,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MapUriResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImageryMetadataResponse))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ResponseBase {
        
        private ResponseSummary responseSummaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseSummary ResponseSummary {
            get {
                return this.responseSummaryField;
            }
            set {
                this.responseSummaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class MapUriResponse : ResponseBase {
        
        private string uriField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class ImageryMetadataResponse : ResponseBase {
        
        private ImageryMetadataResult[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ImageryMetadataResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Pushpin {
        
        private string iconStyleField;
        
        private string labelField;
        
        private Location locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IconStyle {
            get {
                return this.iconStyleField;
            }
            set {
                this.iconStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class MapUriOptions {
        
        private string[] displayLayersField;
        
        private SizeOfint imageSizeField;
        
        private ImageType imageTypeField;
        
        private bool imageTypeFieldSpecified;
        
        private bool preventIconCollisionField;
        
        private bool preventIconCollisionFieldSpecified;
        
        private MapStyle styleField;
        
        private bool styleFieldSpecified;
        
        private UriScheme uriSchemeField;
        
        private bool uriSchemeFieldSpecified;
        
        private System.Nullable<int> zoomLevelField;
        
        private bool zoomLevelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] DisplayLayers {
            get {
                return this.displayLayersField;
            }
            set {
                this.displayLayersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SizeOfint ImageSize {
            get {
                return this.imageSizeField;
            }
            set {
                this.imageSizeField = value;
            }
        }
        
        /// <remarks/>
        public ImageType ImageType {
            get {
                return this.imageTypeField;
            }
            set {
                this.imageTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImageTypeSpecified {
            get {
                return this.imageTypeFieldSpecified;
            }
            set {
                this.imageTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PreventIconCollision {
            get {
                return this.preventIconCollisionField;
            }
            set {
                this.preventIconCollisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreventIconCollisionSpecified {
            get {
                return this.preventIconCollisionFieldSpecified;
            }
            set {
                this.preventIconCollisionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public MapStyle Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StyleSpecified {
            get {
                return this.styleFieldSpecified;
            }
            set {
                this.styleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public UriScheme UriScheme {
            get {
                return this.uriSchemeField;
            }
            set {
                this.uriSchemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UriSchemeSpecified {
            get {
                return this.uriSchemeFieldSpecified;
            }
            set {
                this.uriSchemeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ZoomLevel {
            get {
                return this.zoomLevelField;
            }
            set {
                this.zoomLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZoomLevelSpecified {
            get {
                return this.zoomLevelFieldSpecified;
            }
            set {
                this.zoomLevelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum ImageType {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Png,
        
        /// <remarks/>
        Jpeg,
        
        /// <remarks/>
        Gif,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum MapStyle {
        
        /// <remarks/>
        Road,
        
        /// <remarks/>
        Aerial,
        
        /// <remarks/>
        AerialWithLabels,
        
        /// <remarks/>
        Birdseye,
        
        /// <remarks/>
        BirdseyeWithLabels,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum UriScheme {
        
        /// <remarks/>
        Http,
        
        /// <remarks/>
        Https,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserProfile {
        
        private Heading currentHeadingField;
        
        private UserLocation currentLocationField;
        
        private DeviceType deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private DistanceUnit distanceUnitField;
        
        private bool distanceUnitFieldSpecified;
        
        private string iPAddressField;
        
        private ShapeBase mapViewField;
        
        private SizeOfint screenSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Heading CurrentHeading {
            get {
                return this.currentHeadingField;
            }
            set {
                this.currentHeadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserLocation CurrentLocation {
            get {
                return this.currentLocationField;
            }
            set {
                this.currentLocationField = value;
            }
        }
        
        /// <remarks/>
        public DeviceType DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeviceTypeSpecified {
            get {
                return this.deviceTypeFieldSpecified;
            }
            set {
                this.deviceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DistanceUnit DistanceUnit {
            get {
                return this.distanceUnitField;
            }
            set {
                this.distanceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceUnitSpecified {
            get {
                return this.distanceUnitFieldSpecified;
            }
            set {
                this.distanceUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ShapeBase MapView {
            get {
                return this.mapViewField;
            }
            set {
                this.mapViewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SizeOfint ScreenSize {
            get {
                return this.screenSizeField;
            }
            set {
                this.screenSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DeviceType {
        
        /// <remarks/>
        Desktop,
        
        /// <remarks/>
        Mobile,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ExecutionOptions {
        
        private bool suppressFaultsField;
        
        private bool suppressFaultsFieldSpecified;
        
        /// <remarks/>
        public bool SuppressFaults {
            get {
                return this.suppressFaultsField;
            }
            set {
                this.suppressFaultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuppressFaultsSpecified {
            get {
                return this.suppressFaultsFieldSpecified;
            }
            set {
                this.suppressFaultsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Credentials {
        
        private string applicationIdField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MapUriRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ImageryMetadataRequest))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class RequestBase {
        
        private Credentials credentialsField;
        
        private string cultureField;
        
        private ExecutionOptions executionOptionsField;
        
        private UserProfile userProfileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Credentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExecutionOptions ExecutionOptions {
            get {
                return this.executionOptionsField;
            }
            set {
                this.executionOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserProfile UserProfile {
            get {
                return this.userProfileField;
            }
            set {
                this.userProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class MapUriRequest : RequestBase {
        
        private Location centerField;
        
        private Location majorRoutesDestinationField;
        
        private MapUriOptions optionsField;
        
        private Pushpin[] pushpinsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location MajorRoutesDestination {
            get {
                return this.majorRoutesDestinationField;
            }
            set {
                this.majorRoutesDestinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MapUriOptions Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
        public Pushpin[] Pushpins {
            get {
                return this.pushpinsField;
            }
            set {
                this.pushpinsField = value;
            }
        }
    }
}
