//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3082.
// 
namespace Ushahidi.Map.Search.Staging {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISearchService", Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FilterValue))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestBase))]
    public partial class SearchService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SearchService() {
            this.Url = "http://staging.dev.virtualearth.net/webservices/v1/searchservice/searchservice.sv" +
                "c";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://dev.virtualearth.net/webservices/v1/search/contracts/ISearchService/Search" +
            "", RequestNamespace="http://dev.virtualearth.net/webservices/v1/search/contracts", ResponseNamespace="http://dev.virtualearth.net/webservices/v1/search/contracts", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SearchResponse Search([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SearchRequest request) {
            object[] results = this.Invoke("Search", new object[] {
                        request});
            return ((SearchResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearch(SearchRequest request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Search", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public SearchResponse EndSearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SearchResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class SearchRequest : RequestBase {
        
        private string queryField;
        
        private SearchOptions searchOptionsField;
        
        private StructuredSearchQuery structuredQueryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SearchOptions SearchOptions {
            get {
                return this.searchOptionsField;
            }
            set {
                this.searchOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StructuredSearchQuery StructuredQuery {
            get {
                return this.structuredQueryField;
            }
            set {
                this.structuredQueryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class SearchOptions {
        
        private System.Nullable<bool> autocorrectQueryField;
        
        private bool autocorrectQueryFieldSpecified;
        
        private System.Nullable<int> countField;
        
        private bool countFieldSpecified;
        
        private FilterExpressionBase filtersField;
        
        private ListingType listingTypeField;
        
        private bool listingTypeFieldSpecified;
        
        private bool parseOnlyField;
        
        private bool parseOnlyFieldSpecified;
        
        private SortOrder sortOrderField;
        
        private bool sortOrderFieldSpecified;
        
        private int startingIndexField;
        
        private bool startingIndexFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> AutocorrectQuery {
            get {
                return this.autocorrectQueryField;
            }
            set {
                this.autocorrectQueryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutocorrectQuerySpecified {
            get {
                return this.autocorrectQueryFieldSpecified;
            }
            set {
                this.autocorrectQueryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FilterExpressionBase Filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
            }
        }
        
        /// <remarks/>
        public ListingType ListingType {
            get {
                return this.listingTypeField;
            }
            set {
                this.listingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListingTypeSpecified {
            get {
                return this.listingTypeFieldSpecified;
            }
            set {
                this.listingTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ParseOnly {
            get {
                return this.parseOnlyField;
            }
            set {
                this.parseOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParseOnlySpecified {
            get {
                return this.parseOnlyFieldSpecified;
            }
            set {
                this.parseOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SortOrder SortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SortOrderSpecified {
            get {
                return this.sortOrderFieldSpecified;
            }
            set {
                this.sortOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int StartingIndex {
            get {
                return this.startingIndexField;
            }
            set {
                this.startingIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartingIndexSpecified {
            get {
                return this.startingIndexFieldSpecified;
            }
            set {
                this.startingIndexFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FilterExpressionClause))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FilterExpression))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class FilterExpressionBase {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class FilterValue {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class LocationData {
        
        private Confidence confidenceField;
        
        private bool confidenceFieldSpecified;
        
        private GeocodeLocation[] locationsField;
        
        private string[] matchCodesField;
        
        /// <remarks/>
        public Confidence Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfidenceSpecified {
            get {
                return this.confidenceFieldSpecified;
            }
            set {
                this.confidenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
        public GeocodeLocation[] Locations {
            get {
                return this.locationsField;
            }
            set {
                this.locationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] MatchCodes {
            get {
                return this.matchCodesField;
            }
            set {
                this.matchCodesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum Confidence {
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class GeocodeLocation : Location {
        
        private string calculationMethodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CalculationMethod {
            get {
                return this.calculationMethodField;
            }
            set {
                this.calculationMethodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GeocodeLocation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserLocation))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Location {
        
        private double altitudeField;
        
        private bool altitudeFieldSpecified;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        /// <remarks/>
        public double Altitude {
            get {
                return this.altitudeField;
            }
            set {
                this.altitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AltitudeSpecified {
            get {
                return this.altitudeFieldSpecified;
            }
            set {
                this.altitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserLocation : Location {
        
        private Confidence confidenceField;
        
        private bool confidenceFieldSpecified;
        
        /// <remarks/>
        public Confidence Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfidenceSpecified {
            get {
                return this.confidenceFieldSpecified;
            }
            set {
                this.confidenceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonSearchResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessSearchResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CommunityContentSearchResult))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class SearchResultBase {
        
        private double distanceField;
        
        private bool distanceFieldSpecified;
        
        private string idField;
        
        private LocationData locationDataField;
        
        private string nameField;
        
        /// <remarks/>
        public double Distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceSpecified {
            get {
                return this.distanceFieldSpecified;
            }
            set {
                this.distanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public LocationData LocationData {
            get {
                return this.locationDataField;
            }
            set {
                this.locationDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class PersonSearchResult : SearchResultBase {
        
        private Address addressField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Address {
        
        private string addressLineField;
        
        private string adminDistrictField;
        
        private string countryRegionField;
        
        private string districtField;
        
        private string formattedAddressField;
        
        private string localityField;
        
        private string postalCodeField;
        
        private string postalTownField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdminDistrict {
            get {
                return this.adminDistrictField;
            }
            set {
                this.adminDistrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryRegion {
            get {
                return this.countryRegionField;
            }
            set {
                this.countryRegionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FormattedAddress {
            get {
                return this.formattedAddressField;
            }
            set {
                this.formattedAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostalTown {
            get {
                return this.postalTownField;
            }
            set {
                this.postalTownField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class BusinessSearchResult : SearchResultBase {
        
        private ArrayOfKeyValueOfstringanyTypeKeyValueOfstringanyType[] additionalPropertiesField;
        
        private Address addressField;
        
        private Category[] categoriesField;
        
        private ArrayOfKeyValueOfintCategorySpecificPropertySetn6Q9q_P9sKeyValueOfintCategorySpecificPropertySetn6Q9q_P9s[] categorySpecificPropertiesField;
        
        private Neighborhood[] neighborhoodsField;
        
        private string phoneNumberField;
        
        private int ratingCountField;
        
        private bool ratingCountFieldSpecified;
        
        private int reviewCountField;
        
        private bool reviewCountFieldSpecified;
        
        private double userRatingField;
        
        private bool userRatingFieldSpecified;
        
        private string websiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringanyType", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringanyTypeKeyValueOfstringanyType[] AdditionalProperties {
            get {
                return this.additionalPropertiesField;
            }
            set {
                this.additionalPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Category[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfintCategorySpecificPropertySetn6Q9q_P9s", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfintCategorySpecificPropertySetn6Q9q_P9sKeyValueOfintCategorySpecificPropertySetn6Q9q_P9s[] CategorySpecificProperties {
            get {
                return this.categorySpecificPropertiesField;
            }
            set {
                this.categorySpecificPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Neighborhood[] Neighborhoods {
            get {
                return this.neighborhoodsField;
            }
            set {
                this.neighborhoodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public int RatingCount {
            get {
                return this.ratingCountField;
            }
            set {
                this.ratingCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RatingCountSpecified {
            get {
                return this.ratingCountFieldSpecified;
            }
            set {
                this.ratingCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ReviewCount {
            get {
                return this.reviewCountField;
            }
            set {
                this.reviewCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReviewCountSpecified {
            get {
                return this.reviewCountFieldSpecified;
            }
            set {
                this.reviewCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double UserRating {
            get {
                return this.userRatingField;
            }
            set {
                this.userRatingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserRatingSpecified {
            get {
                return this.userRatingFieldSpecified;
            }
            set {
                this.userRatingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", IsNullable=true)]
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringanyTypeKeyValueOfstringanyType {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class Category {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfintCategorySpecificPropertySetn6Q9q_P9sKeyValueOfintCategorySpecificPropertySetn6Q9q_P9s {
        
        private int keyField;
        
        private CategorySpecificPropertySet valueField;
        
        /// <remarks/>
        public int Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CategorySpecificPropertySet Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class CategorySpecificPropertySet {
        
        private string categoryNameField;
        
        private ArrayOfKeyValueOfstringanyTypeKeyValueOfstringanyType[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringanyType", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringanyTypeKeyValueOfstringanyType[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class Neighborhood {
        
        private string cityField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class CommunityContentSearchResult : SearchResultBase {
        
        private ArrayOfKeyValueOfstringanyTypeKeyValueOfstringanyType[] additionalPropertiesField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringanyType", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringanyTypeKeyValueOfstringanyType[] AdditionalProperties {
            get {
                return this.additionalPropertiesField;
            }
            set {
                this.additionalPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class Parse {
        
        private Address addressField;
        
        private string keywordField;
        
        private string landmarkField;
        
        private string locationSeparatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Landmark {
            get {
                return this.landmarkField;
            }
            set {
                this.landmarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LocationSeparator {
            get {
                return this.locationSeparatorField;
            }
            set {
                this.locationSeparatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class CategoryCount {
        
        private Category categoryField;
        
        private int countField;
        
        private bool countFieldSpecified;
        
        private ArrayOfKeyValueOfNeighborhoodintkC8b0tr6KeyValueOfNeighborhoodintkC8b0tr6[] countByNeighborhoodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Category Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfNeighborhoodintkC8b0tr6", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfNeighborhoodintkC8b0tr6KeyValueOfNeighborhoodintkC8b0tr6[] CountByNeighborhood {
            get {
                return this.countByNeighborhoodField;
            }
            set {
                this.countByNeighborhoodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfNeighborhoodintkC8b0tr6KeyValueOfNeighborhoodintkC8b0tr6 {
        
        private Neighborhood keyField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Neighborhood Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValueListFilter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RangeFilter))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class AvailableFilter {
        
        private int propertyIdField;
        
        private bool propertyIdFieldSpecified;
        
        private string propertyNameField;
        
        /// <remarks/>
        public int PropertyId {
            get {
                return this.propertyIdField;
            }
            set {
                this.propertyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PropertyIdSpecified {
            get {
                return this.propertyIdFieldSpecified;
            }
            set {
                this.propertyIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class ValueListFilter : AvailableFilter {
        
        private object[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public object[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class RangeFilter : AvailableFilter {
        
        private object maximumValueField;
        
        private object minimumValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object MaximumValue {
            get {
                return this.maximumValueField;
            }
            set {
                this.maximumValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object MinimumValue {
            get {
                return this.minimumValueField;
            }
            set {
                this.minimumValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class GeocodeResult {
        
        private Address addressField;
        
        private Rectangle bestViewField;
        
        private Confidence confidenceField;
        
        private bool confidenceFieldSpecified;
        
        private string displayNameField;
        
        private string entityTypeField;
        
        private GeocodeLocation[] locationsField;
        
        private string[] matchCodesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Rectangle BestView {
            get {
                return this.bestViewField;
            }
            set {
                this.bestViewField = value;
            }
        }
        
        /// <remarks/>
        public Confidence Confidence {
            get {
                return this.confidenceField;
            }
            set {
                this.confidenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConfidenceSpecified {
            get {
                return this.confidenceFieldSpecified;
            }
            set {
                this.confidenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EntityType {
            get {
                return this.entityTypeField;
            }
            set {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public GeocodeLocation[] Locations {
            get {
                return this.locationsField;
            }
            set {
                this.locationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] MatchCodes {
            get {
                return this.matchCodesField;
            }
            set {
                this.matchCodesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Rectangle : ShapeBase {
        
        private Location northeastField;
        
        private Location southwestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Northeast {
            get {
                return this.northeastField;
            }
            set {
                this.northeastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Southwest {
            get {
                return this.southwestField;
            }
            set {
                this.southwestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Polygon))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Circle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rectangle))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ShapeBase {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Polygon : ShapeBase {
        
        private Location[] verticesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Location[] Vertices {
            get {
                return this.verticesField;
            }
            set {
                this.verticesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Circle : ShapeBase {
        
        private Location centerField;
        
        private DistanceUnit distanceUnitField;
        
        private bool distanceUnitFieldSpecified;
        
        private double radiusField;
        
        private bool radiusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location Center {
            get {
                return this.centerField;
            }
            set {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        public DistanceUnit DistanceUnit {
            get {
                return this.distanceUnitField;
            }
            set {
                this.distanceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceUnitSpecified {
            get {
                return this.distanceUnitFieldSpecified;
            }
            set {
                this.distanceUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Radius {
            get {
                return this.radiusField;
            }
            set {
                this.radiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RadiusSpecified {
            get {
                return this.radiusFieldSpecified;
            }
            set {
                this.radiusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DistanceUnit {
        
        /// <remarks/>
        Kilometer,
        
        /// <remarks/>
        Mile,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class SearchRegion {
        
        private ShapeBase boundingAreaField;
        
        private GeocodeResult geocodeLocationField;
        
        private string sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ShapeBase BoundingArea {
            get {
                return this.boundingAreaField;
            }
            set {
                this.boundingAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GeocodeResult GeocodeLocation {
            get {
                return this.geocodeLocationField;
            }
            set {
                this.geocodeLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class SearchResultSet {
        
        private SearchRegion[] alternateSearchRegionsField;
        
        private AvailableFilter[] availableFiltersField;
        
        private CategoryCount[] categoryCountsField;
        
        private int estimatedMatchesField;
        
        private bool estimatedMatchesFieldSpecified;
        
        private string listingTypeField;
        
        private Parse parseField;
        
        private bool queryCorrectedField;
        
        private bool queryCorrectedFieldSpecified;
        
        private SearchResultBase[] resultsField;
        
        private SearchRegion searchRegionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SearchRegion[] AlternateSearchRegions {
            get {
                return this.alternateSearchRegionsField;
            }
            set {
                this.alternateSearchRegionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public AvailableFilter[] AvailableFilters {
            get {
                return this.availableFiltersField;
            }
            set {
                this.availableFiltersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CategoryCount[] CategoryCounts {
            get {
                return this.categoryCountsField;
            }
            set {
                this.categoryCountsField = value;
            }
        }
        
        /// <remarks/>
        public int EstimatedMatches {
            get {
                return this.estimatedMatchesField;
            }
            set {
                this.estimatedMatchesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstimatedMatchesSpecified {
            get {
                return this.estimatedMatchesFieldSpecified;
            }
            set {
                this.estimatedMatchesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListingType {
            get {
                return this.listingTypeField;
            }
            set {
                this.listingTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Parse Parse {
            get {
                return this.parseField;
            }
            set {
                this.parseField = value;
            }
        }
        
        /// <remarks/>
        public bool QueryCorrected {
            get {
                return this.queryCorrectedField;
            }
            set {
                this.queryCorrectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QueryCorrectedSpecified {
            get {
                return this.queryCorrectedFieldSpecified;
            }
            set {
                this.queryCorrectedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SearchResultBase[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SearchRegion SearchRegion {
            get {
                return this.searchRegionField;
            }
            set {
                this.searchRegionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class StructuredSearchQuery {
        
        private string keywordField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Keyword {
            get {
                return this.keywordField;
            }
            set {
                this.keywordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class QuerySuggestion {
        
        private string queryField;
        
        private StructuredSearchQuery structuredQueryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Query {
            get {
                return this.queryField;
            }
            set {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StructuredSearchQuery StructuredQuery {
            get {
                return this.structuredQueryField;
            }
            set {
                this.structuredQueryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ResponseSummary {
        
        private AuthenticationResultCode authenticationResultCodeField;
        
        private bool authenticationResultCodeFieldSpecified;
        
        private string copyrightField;
        
        private string faultReasonField;
        
        private ResponseStatusCode statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string traceIdField;
        
        /// <remarks/>
        public AuthenticationResultCode AuthenticationResultCode {
            get {
                return this.authenticationResultCodeField;
            }
            set {
                this.authenticationResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AuthenticationResultCodeSpecified {
            get {
                return this.authenticationResultCodeFieldSpecified;
            }
            set {
                this.authenticationResultCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FaultReason {
            get {
                return this.faultReasonField;
            }
            set {
                this.faultReasonField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatusCode StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TraceId {
            get {
                return this.traceIdField;
            }
            set {
                this.traceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum AuthenticationResultCode {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        NoCredentials,
        
        /// <remarks/>
        ValidCredentials,
        
        /// <remarks/>
        InvalidCredentials,
        
        /// <remarks/>
        CredentialsExpired,
        
        /// <remarks/>
        NotAuthorized,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum ResponseStatusCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        ServerError,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchResponse))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ResponseBase {
        
        private ResponseSummary responseSummaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseSummary ResponseSummary {
            get {
                return this.responseSummaryField;
            }
            set {
                this.responseSummaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class SearchResponse : ResponseBase {
        
        private QuerySuggestion querySuggestionField;
        
        private SearchResultSet[] resultSetsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public QuerySuggestion QuerySuggestion {
            get {
                return this.querySuggestionField;
            }
            set {
                this.querySuggestionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SearchResultSet[] ResultSets {
            get {
                return this.resultSetsField;
            }
            set {
                this.resultSetsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class SizeOfint {
        
        private int heightField;
        
        private bool heightFieldSpecified;
        
        private int widthField;
        
        private bool widthFieldSpecified;
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Heading {
        
        private double orientationField;
        
        private bool orientationFieldSpecified;
        
        /// <remarks/>
        public double Orientation {
            get {
                return this.orientationField;
            }
            set {
                this.orientationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrientationSpecified {
            get {
                return this.orientationFieldSpecified;
            }
            set {
                this.orientationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserProfile {
        
        private Heading currentHeadingField;
        
        private UserLocation currentLocationField;
        
        private DeviceType deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private DistanceUnit distanceUnitField;
        
        private bool distanceUnitFieldSpecified;
        
        private string iPAddressField;
        
        private ShapeBase mapViewField;
        
        private SizeOfint screenSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Heading CurrentHeading {
            get {
                return this.currentHeadingField;
            }
            set {
                this.currentHeadingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserLocation CurrentLocation {
            get {
                return this.currentLocationField;
            }
            set {
                this.currentLocationField = value;
            }
        }
        
        /// <remarks/>
        public DeviceType DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeviceTypeSpecified {
            get {
                return this.deviceTypeFieldSpecified;
            }
            set {
                this.deviceTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DistanceUnit DistanceUnit {
            get {
                return this.distanceUnitField;
            }
            set {
                this.distanceUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DistanceUnitSpecified {
            get {
                return this.distanceUnitFieldSpecified;
            }
            set {
                this.distanceUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ShapeBase MapView {
            get {
                return this.mapViewField;
            }
            set {
                this.mapViewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SizeOfint ScreenSize {
            get {
                return this.screenSizeField;
            }
            set {
                this.screenSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DeviceType {
        
        /// <remarks/>
        Desktop,
        
        /// <remarks/>
        Mobile,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ExecutionOptions {
        
        private bool suppressFaultsField;
        
        private bool suppressFaultsFieldSpecified;
        
        /// <remarks/>
        public bool SuppressFaults {
            get {
                return this.suppressFaultsField;
            }
            set {
                this.suppressFaultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuppressFaultsSpecified {
            get {
                return this.suppressFaultsFieldSpecified;
            }
            set {
                this.suppressFaultsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Credentials {
        
        private string applicationIdField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchRequest))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class RequestBase {
        
        private Credentials credentialsField;
        
        private string cultureField;
        
        private ExecutionOptions executionOptionsField;
        
        private UserProfile userProfileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Credentials Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExecutionOptions ExecutionOptions {
            get {
                return this.executionOptionsField;
            }
            set {
                this.executionOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UserProfile UserProfile {
            get {
                return this.userProfileField;
            }
            set {
                this.userProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class FilterExpressionClause : FilterExpressionBase {
        
        private FilterExpressionBase[] expressionsField;
        
        private LogicalOperator logicalOperatorField;
        
        private bool logicalOperatorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public FilterExpressionBase[] Expressions {
            get {
                return this.expressionsField;
            }
            set {
                this.expressionsField = value;
            }
        }
        
        /// <remarks/>
        public LogicalOperator LogicalOperator {
            get {
                return this.logicalOperatorField;
            }
            set {
                this.logicalOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LogicalOperatorSpecified {
            get {
                return this.logicalOperatorFieldSpecified;
            }
            set {
                this.logicalOperatorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum LogicalOperator {
        
        /// <remarks/>
        And,
        
        /// <remarks/>
        Or,
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class FilterExpression : FilterExpressionBase {
        
        private CompareOperator compareOperatorField;
        
        private bool compareOperatorFieldSpecified;
        
        private object filterValueField;
        
        private int propertyIdField;
        
        private bool propertyIdFieldSpecified;
        
        /// <remarks/>
        public CompareOperator CompareOperator {
            get {
                return this.compareOperatorField;
            }
            set {
                this.compareOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CompareOperatorSpecified {
            get {
                return this.compareOperatorFieldSpecified;
            }
            set {
                this.compareOperatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object FilterValue {
            get {
                return this.filterValueField;
            }
            set {
                this.filterValueField = value;
            }
        }
        
        /// <remarks/>
        public int PropertyId {
            get {
                return this.propertyIdField;
            }
            set {
                this.propertyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PropertyIdSpecified {
            get {
                return this.propertyIdFieldSpecified;
            }
            set {
                this.propertyIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum CompareOperator {
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        GreaterThan,
        
        /// <remarks/>
        GreaterThanOrEquals,
        
        /// <remarks/>
        LessThan,
        
        /// <remarks/>
        LessThanOrEquals,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public enum ListingType {
        
        /// <remarks/>
        Business,
        
        /// <remarks/>
        CommunityContent,
        
        /// <remarks/>
        Person,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public enum SortOrder {
        
        /// <remarks/>
        Relevance,
        
        /// <remarks/>
        Distance,
        
        /// <remarks/>
        Rating,
        
        /// <remarks/>
        Popularity,
    }
}
